# Generated by Django 5.1.6 on 2026-04-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = []
