# Generated by Django 5.1.6 on 2026-04-06 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_medicamento_laboratorio_medicamento_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('laboratorio', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_generico', models.CharField(max_length=255, unique=True)),
                ('concentracion', models.CharField(max_length=100)),
                ('forma_farmaceutica', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.AddField(
            model_name='medicamentocomercial',
            name='generico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='inventarios.medicamentogenerico'),
        ),
    ]
