# Generated by Django 5.1.6 on 2026-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradastock',
            name='motivo',
            field=models.CharField(choices=[('reposicion', 'Reposición Proveedor'), ('devolucion', 'Devolución de Cliente'), ('ajuste', 'Ajuste de Inventario'), ('correccion', 'Corrección de Conteo'), ('otro', 'Otro')], max_length=20),
        ),
    ]
